
-- Add new columns for remaining 6 categories
ALTER TABLE public.listings
  ADD COLUMN IF NOT EXISTS condition text,
  ADD COLUMN IF NOT EXISTS listing_type_item text,
  ADD COLUMN IF NOT EXISTS swap_for text,
  ADD COLUMN IF NOT EXISTS quantity integer DEFAULT 1,
  ADD COLUMN IF NOT EXISTS has_warranty boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS warranty_expiry date,
  ADD COLUMN IF NOT EXISTS warranty_type text,
  ADD COLUMN IF NOT EXISTS reason_selling text,
  ADD COLUMN IF NOT EXISTS brand text,
  ADD COLUMN IF NOT EXISTS item_model text,
  ADD COLUMN IF NOT EXISTS item_color text,
  ADD COLUMN IF NOT EXISTS item_size text,
  ADD COLUMN IF NOT EXISTS item_material text,
  ADD COLUMN IF NOT EXISTS item_type text,
  ADD COLUMN IF NOT EXISTS processor text,
  ADD COLUMN IF NOT EXISTS ram text,
  ADD COLUMN IF NOT EXISTS storage_capacity text,
  ADD COLUMN IF NOT EXISTS storage_type text,
  ADD COLUMN IF NOT EXISTS gpu text,
  ADD COLUMN IF NOT EXISTS screen_size text,
  ADD COLUMN IF NOT EXISTS operating_system text,
  ADD COLUMN IF NOT EXISTS battery_health text,
  ADD COLUMN IF NOT EXISTS network_type text[],
  ADD COLUMN IF NOT EXISTS sim_type text,
  ADD COLUMN IF NOT EXISTS unlocked boolean,
  ADD COLUMN IF NOT EXISTS accessories_included text[],
  ADD COLUMN IF NOT EXISTS service_direction text,
  ADD COLUMN IF NOT EXISTS pricing_type text,
  ADD COLUMN IF NOT EXISTS availability text[],
  ADD COLUMN IF NOT EXISTS service_location text[],
  ADD COLUMN IF NOT EXISTS experience_level text,
  ADD COLUMN IF NOT EXISTS service_languages text[],
  ADD COLUMN IF NOT EXISTS portfolio_url text,
  ADD COLUMN IF NOT EXISTS business_type text,
  ADD COLUMN IF NOT EXISTS annual_revenue numeric,
  ADD COLUMN IF NOT EXISTS monthly_rent numeric,
  ADD COLUMN IF NOT EXISTS lease_remaining text,
  ADD COLUMN IF NOT EXISTS employee_count text,
  ADD COLUMN IF NOT EXISTS years_in_operation text,
  ADD COLUMN IF NOT EXISTS business_includes text[],
  ADD COLUMN IF NOT EXISTS unit_of_measurement text,
  ADD COLUMN IF NOT EXISTS min_order_quantity integer,
  ADD COLUMN IF NOT EXISTS delivery_available text,
  ADD COLUMN IF NOT EXISTS stock_status text,
  ADD COLUMN IF NOT EXISTS dimensions_w numeric,
  ADD COLUMN IF NOT EXISTS dimensions_h numeric,
  ADD COLUMN IF NOT EXISTS dimensions_d numeric,
  ADD COLUMN IF NOT EXISTS assembly_required text,
  ADD COLUMN IF NOT EXISTS item_set boolean,
  ADD COLUMN IF NOT EXISTS set_pieces text,
  ADD COLUMN IF NOT EXISTS energy_rating text,
  ADD COLUMN IF NOT EXISTS smart_device boolean;
